### ISSUE TITLE
¿Cuál es el estado actual de este proyecto?

### ISSUE THREAD

**Issue by santilin** [olea/lemarios#7]
Me gustaría saber si se ha movido a otro sitio, o se ha integrado con openoffice, o cualquier otra cosa.

**Comment by rlunaro** [comment]
creo que no lo atiende ni el propio autor. Algún interés en este tema?

**Comment by santilin** [comment]
Hola Mundo
Hola Mundo 	
*web - programación - marketing digital*

Hola Raúl,

pues sí, tengo el interés de dedicar algo de tiempo a esto. Me gustan 
los juegos de palabras y estoy pensando en ayudar a hacer un comprobador 
de sintaxis y de gramática para el español.

¿Conoces otros proyectos relacionados?

Un saludo.

*Santiago Capel Torres* 	teléfono*868 074 070* 	*holamundo.me 
<http://www.holamundo.me>*

*Aviso legal* · Este mensaje se dirige exclusivamente a su destinatario 
y puede contener información privilegiada o confidencial. Si no es vd. 
el destinatario indicado, queda notificado de que la lectura, 
utilización, divulgación y/o copia sin autorización está prohibida en 
virtud de la legislación vigente. Si ha recibido este mensaje por error, 
le rogamos que nos lo comunique inmediatamente por esta misma vía y 
proceda a su destrucción.

**Comment by rlunaro** [comment]
Hace un tiempo yo estuve investigando en el asunto y no encontré nada excepto una lista de apellidos y de topónimos. Pregunté a la RAE si liberan su diccionario en formato digital: me dijeron que en la próxima edición (que es ésta). Pero no investigué más porque mis intereses cambiaron.

**Comment by santilin** [comment]
Ah, gracias, voy a preguntarles y te digo lo que me contesten.

**Comment by olea** [comment]
@santilin 
> Me gustaría saber si se ha movido a otro sitio, o se ha integrado con openoffice, o cualquier otra cosa.

Hola:
Estas recopilaciones no tienen mucha actividad porque tampoco se suelen recibir contribuciones.

Sobre integración en proyectos, dado que se quiere usar licencias CC0 es posible integrar/reutilizar en cualquier parte, como en el proyecto [RLA](https://github.com/sbosio/rla-es).

**Comment by olea** [comment]
@rlunaro 
> creo que no lo atiende ni el propio autor. Algún interés en este tema?

tienes razón; desgraciadamente no he pasado por los mejores momentos de mi vida.

**Comment by olea** [comment]
@rlunaro 

> Hace un tiempo yo estuve investigando en el asunto y no encontré nada excepto una lista de apellidos y de topónimos. Pregunté a la RAE si liberan su diccionario en formato digital: me dijeron que en la próxima edición (que es ésta). Pero no investigué más porque mis intereses cambiaron.

Según mi experiencia la RAE __jamás__ publicará recursos abiertos de libre uso. Es dolorosamente lamentable.

Por eso que al final todos acabamos buscando el camino de enmedio.

**Comment by santilin** [comment]
Efectivamente, aún no me han respondido. Gracias por el enlace al proyecto RLA, es exactamente lo que buscaba.

**Comment by olea** [comment]
> Gracias por el enlace al proyecto RLA, es exactamente lo que buscaba.

Genial.

De todas formas, si tienes listas de palabras que compartir puedes hacerlo también a través de este grupo al margen de ser usadas en RLA. Aquí procuramos usar licencias más laxas (a priori CC-0) que la GPL que usa RLA.
